site_name: 我的信息展示页面

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换到暗黑模式

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: 切换到亮色模式

nav:
  - 首页: index.md
  - 玻璃文档: bolli.md
  - 七年级: 七年级.md
  - 初学 Markdown: 初学markdown.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css